/**
 * 都道府県コード
 */
export const PREFECTURE_CODES = {
  HOKKAIDO: '01',
  AOMORI: '02',
  IWATE: '03',
  MIYAGI: '04',
  AKITA: '05',
  YAMAGATA: '06',
  FUKUSHIMA: '07',
  IBARAKI: '08',
  TOCHIGI: '09',
  GUMMA: '10',
  SAITAMA: '11',
  CHIBA: '12',
  TOKYO: '13',
  KANAGAWA: '14',
  NIGATA: '15',
  TOYAMA: '16',
  ISHIKAWA: '17',
  FUKUI: '18',
  YAMANASHI: '19',
  NAGANO: '20',
  GIFU: '21',
  SHIZUOKA: '22',
  AICHI: '23',
  MIE: '24',
  SHIGA: '25',
  KYOTO: '26',
  OSAKA: '27',
  HYOGO: '28',
  NARA: '29',
  WAKAYAMA: '30',
  TOTTORI: '31',
  SHIMANE: '32',
  OKAYAMA: '33',
  HIROSHIMA: '34',
  YAMAGUCHI: '35',
  TOKUSHIMA: '36',
  KAGAWA: '37',
  EHIME: '38',
  KOCHI: '39',
  FUKUOKA: '40',
  SAGA: '41',
  NAGASAKI: '42',
  KUMAMOTO: '43',
  OITA: '44',
  MIYAZAKI: '45',
  KAGOSHIMA: '46',
  OKINAWA: '47',
} as const satisfies Record<string, string>

type Prefectures = keyof typeof PREFECTURE_CODES

/**
 * 都道府県一覧
 */
export const PREFECTURE_LIST = [
  { value: PREFECTURE_CODES.HOKKAIDO, label: '北海道' },
  { value: PREFECTURE_CODES.AOMORI, label: '青森県' },
  { value: PREFECTURE_CODES.IWATE, label: '岩手県' },
  { value: PREFECTURE_CODES.MIYAGI, label: '宮城県' },
  { value: PREFECTURE_CODES.AKITA, label: '秋田県' },
  { value: PREFECTURE_CODES.YAMAGATA, label: '山形県' },
  { value: PREFECTURE_CODES.FUKUSHIMA, label: '福島県' },
  { value: PREFECTURE_CODES.IBARAKI, label: '茨城県' },
  { value: PREFECTURE_CODES.TOCHIGI, label: '栃木県' },
  { value: PREFECTURE_CODES.GUMMA, label: '群馬県' },
  { value: PREFECTURE_CODES.SAITAMA, label: '埼玉県' },
  { value: PREFECTURE_CODES.CHIBA, label: '千葉県' },
  { value: PREFECTURE_CODES.TOKYO, label: '東京都' },
  { value: PREFECTURE_CODES.KANAGAWA, label: '神奈川県' },
  { value: PREFECTURE_CODES.NIGATA, label: '新潟県' },
  { value: PREFECTURE_CODES.TOYAMA, label: '富山県' },
  { value: PREFECTURE_CODES.ISHIKAWA, label: '石川県' },
  { value: PREFECTURE_CODES.FUKUI, label: '福井県' },
  { value: PREFECTURE_CODES.YAMANASHI, label: '山梨県' },
  { value: PREFECTURE_CODES.NAGANO, label: '長野県' },
  { value: PREFECTURE_CODES.GIFU, label: '岐阜県' },
  { value: PREFECTURE_CODES.SHIZUOKA, label: '静岡県' },
  { value: PREFECTURE_CODES.AICHI, label: '愛知県' },
  { value: PREFECTURE_CODES.MIE, label: '三重県' },
  { value: PREFECTURE_CODES.SHIGA, label: '滋賀県' },
  { value: PREFECTURE_CODES.KYOTO, label: '京都府' },
  { value: PREFECTURE_CODES.OSAKA, label: '大阪府' },
  { value: PREFECTURE_CODES.HYOGO, label: '兵庫県' },
  { value: PREFECTURE_CODES.NARA, label: '奈良県' },
  { value: PREFECTURE_CODES.WAKAYAMA, label: '和歌山県' },
  { value: PREFECTURE_CODES.TOTTORI, label: '鳥取県' },
  { value: PREFECTURE_CODES.SHIMANE, label: '島根県' },
  { value: PREFECTURE_CODES.OKAYAMA, label: '岡山県' },
  { value: PREFECTURE_CODES.HIROSHIMA, label: '広島県' },
  { value: PREFECTURE_CODES.YAMAGUCHI, label: '山口県' },
  { value: PREFECTURE_CODES.TOKUSHIMA, label: '徳島県' },
  { value: PREFECTURE_CODES.KAGAWA, label: '香川県' },
  { value: PREFECTURE_CODES.EHIME, label: '愛媛県' },
  { value: PREFECTURE_CODES.KOCHI, label: '高知県' },
  { value: PREFECTURE_CODES.FUKUOKA, label: '福岡県' },
  { value: PREFECTURE_CODES.SAGA, label: '佐賀県' },
  { value: PREFECTURE_CODES.NAGASAKI, label: '長崎県' },
  { value: PREFECTURE_CODES.KUMAMOTO, label: '熊本県' },
  { value: PREFECTURE_CODES.OITA, label: '大分県' },
  { value: PREFECTURE_CODES.MIYAZAKI, label: '宮崎県' },
  { value: PREFECTURE_CODES.KAGOSHIMA, label: '鹿児島県' },
  { value: PREFECTURE_CODES.OKINAWA, label: '沖縄県' },
] as const satisfies readonly {
  value: (typeof PREFECTURE_CODES)[Prefectures]
  label: string
}[]
